### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by marcinjahn**

### CODE REVIEW

**Comment by seblj** [comment]
Thanks!

**Comment by marcinjahn** [comment]
@seblj, is there any way to submit issues? I've just discovered this fork, I see it's quite a bit ahead from https://github.com/jmederosalvarado/roslyn.nvim, however the issue I submitted there (https://github.com/jmederosalvarado/roslyn.nvim/issues/40) applies here as well.

Basically, only the old roslyn version works "fully", while the latest one downloaded from the MS feed doesn't.

With the old Roslyn (4.9):
image


With the new Roslyn (4.12):

image

**Comment by seblj** [comment]
Hmm interesting🤔 I think the issue tracker is off by default on a fork, but I can turn it on. I believe I downloaded a new version of roslyn earlier this week, and that it still worked just fine. I can try to reproduce the issue this weekend. Feel free to just open an issue so I have it there as well, and I can comment on that and use that as a reference if I need to fix something👍

**Comment by marcinjahn** [comment]
> Hmm interesting🤔 I think the issue tracker is off by default on a fork, but I can turn it on. I believe I downloaded a new version of roslyn earlier this week, and that it still worked just fine. I can try to reproduce the issue this weekend. Feel free to just open an issue so I have it there as well, and I can comment on that and use that as a reference if I need to fix something👍

I'll create an issue as soon as Issues section appears on the repo :smile:

**Comment by seblj** [comment]
The issue tracker should be visible now. I will look into this, but you could also try going into insert mode and then back to normal mode if you haven't already done that. I know that I need to do that sometimes for the diagnostics to be displayed.

It might also be that they have just changed some settings that is needed, because I need to "turn on" dynamic registration for textdocument diagnostics for some reason I don't know: https://github.com/seblj/roslyn.nvim/blob/3fbbd42c420e731b25c42632e9a5ff4a4fc1fc7b/lua/roslyn/init.lua#L99

**Comment by marcinjahn** [comment]
Thanks, I've created the issue https://github.com/seblj/roslyn.nvim/issues/5

**Pull request merged**
