### PR TITLE
feat: expose pipe status for connect with rzls

### PR DESCRIPTION
**Pull request by tris203**
By exposing the pipes we can connect easier

### CODE REVIEW

**Review by seblj — COMMENTED** [review]
Could you just add a small comment on top saying that it is needed to make connections easier for rzls.nvim or something, so that I won't suddenly forget why it is public😅

**Review by seblj — APPROVED** [review]

**Comment by seblj** [comment]
Hopefully the hacky solution can be removed in not too long: https://github.com/dotnet/roslyn/issues/72871#issuecomment-2502365613

😄

**Comment by tris203** [comment]
> Hopefully the hacky solution can be removed in not too long: https://github.com/dotnet/roslyn/issues/72871
> 
> 😄

That would be nice for you. I think we will always need both of our plugins because of the extent of the custom handlers. 

I don't think lspconfjg would want to maintain that

**Comment by seblj** [comment]
Yes, I think so too, but it would simplify the code _a lot_😅

**Pull request merged**
