### PR TITLE
feat: roslyn initializing spinner

### PR DESCRIPTION
**Pull request by GustavEikaas**
Today when opening a .cs file the roslyn lsp will initialize. First starting with a notification saying `Initializing Roslyn client for ...` then a notification saying `Roslyn project initialization complete`. In my projects and I suspect most projects these messages overlap causing 2 notifications to be active at the same time. This isnt a big deal in any regard but has annoyed me enough times to make this PR. I know roslyn lsp doesnt support progress messages so this was the best I could do. 

I purposely didnt make an issue about this upfront because this is highly subjective, but if you like it feel free to merge it. Otherwise just close it

### CODE REVIEW

**Comment by seblj** [comment]
Thanks for the PR! I really like the idea of this, but at the current state I feel that it is even more verbose than what it is currently?

I don't think I like the way it currently looks, but if it is possible to get it to a state where the message itself is updated and that it looks like it is spinning and not creating a new message for each time, then I would like it! I don't know if that is possible with only using `vim.notify` and neovim API or if that means having a dependency on fidget.nvim. What do  you think?

https://github.com/user-attachments/assets/1dddf1b2-4f32-4b04-a3bf-67916ac6d9e4

**Comment by GustavEikaas** [comment]
I see your point, it didnt occur to me that it wouldnt work with the inbuild notify mechanism. This is what it looks like if you use noice or inbuilt 

## Noice
https://github.com/user-attachments/assets/8e675733-bff2-41c0-9036-2c2f05731100

## inbuilt notify
https://github.com/user-attachments/assets/2d955680-c1ef-4202-aaa2-539163ef7eff

Seems like its not possible to make the notifications update itself using the inbuilt notification so I guess its not worth spending too much time on this. There are so many different notification libraries that making something that works for all of them is probably not worth it.

Putting a dependency on a specific notification lib is also not a good way to go IMO

Thanks for the discussion, I might be back with a better PR at some point if I think of something smart

**Comment by seblj** [comment]
> Putting a dependency on a specific notification lib is also not a good way to go IMO

Yeah I agree.

> Thanks for the discussion, I might be back with a better PR at some point if I think of something smart

Alright, that sounds good! Do young want to keep this open in case or will you just open a new one in that case?

**Comment by GustavEikaas** [comment]
Ill just close it and open a new one if I think of something better

**Comment by seblj** [comment]
Sounds good!

**Pull request closed without merging**
