### PR TITLE
fix: orphaned roslyn processes when opening multiple files

### PR DESCRIPTION
**Pull request by tris203**
Problem: Mulltiple calls to lsp.start from opening multiple files at oncee with the same root_dir config could cause extra orphaned roslyn processes to be spawned

Solution: delay starting roslyn if a start is already in progress as this might be the server you need

opening as a draft, as this might warrant some more discussion

### CODE REVIEW

**Comment by seblj** [comment]
Interesting🤔 how are you opening multiple files at once so that this is happening? How does this work for a server where it doesn't need extra hacks to start, where it is possible to just start it with `vim.lsp.start`? For example pyright, gopls or rust_analyzer

**Comment by tris203** [comment]
It's part of the rzls initialisation

It spawns a '__virtual.cs' file (a compiler generated c reprensention of the file) for each cshtml/razor file in your project and sends a textDocument/didOpen for all of them simultaneously 

I think if it didn't have to have the pipe wrapping it would be fast enough. But because we spawn the command and wait for the pipe info all the spawns come in at the same time (with the same workspaces/rootdir into) and overwrite each other in the _pipes lookup

**Comment by seblj** [comment]
Yeah okay that makes sense. I tried to just look at this code on my phone and I just couldn't remember what the `save_server_object` method was, and especially curious as to why I had exposed it.

Found out that I don't think it is necessary and created a PR to not expose this and move a callback into the server logic.

I did this because I was a bit unsure if the best way to set `start_pending` to false was inside that method. I think we should maybe set it to false no matter if `vim.lsp.start` fails or not(?). That means we can rebase this PR on top of my changes when I merge them, and just set it to false after `vim.lsp.start`.

What do you think?

**Comment by tris203** [comment]
Yes that works. 
That is better as this doesn't handle a failure case very well at the moment

**Comment by seblj** [comment]
Perfect, I just merged it so just rebase and then I can merge!

**Comment by seblj** [comment]
This seems good to me🤷‍♂️ It doesn't really seem to affect things that are not using your rzls plugin. Just let me know if you are done and if it's ready, then I'll merge it

**Comment by tris203** [comment]
Yes, I don't think it will come up under 'normal' operation

Good to go from me

**Pull request merged**
